### ISSUE TITLE
Host key Verification Failed issue

### ISSUE THREAD

**Issue by localgod** [gcavalcante8808/docker-semaphore#4]
I downloaded and ran semaphore and everything seems to work out of the box until I tried running a task.
Then I notices you section about Host key Verification Failed and tried all you suggestion. Sadly I did not made any of them work. Maybe I have misunderstood something. Could you give me a hint?

http://www.dumpt.com/img/viewer.php?file=7lob8xc7qldgggbnyje3.png
http://www.dumpt.com/img/viewer.php?file=u8ezsyes6caarftmak5w.png
http://www.dumpt.com/img/viewer.php?file=dvm885fk8vo0leou1lf8.png

**Comment by gcavalcante8808** [comment]
Hello Friend,

You can save the target's public key before the connection through the following command (as stated in the readme):

docker exec -it <CONTAINER> sh -c 'ssh-keyscan -H <SERVER> >> ~/.ssh/known_hosts'

Otherwise, the parameters present on the environment are applied to ansible connections not the git clone step, thats why the clone step wont work.

**Comment by localgod** [comment]
This dos not seem to work in my setup.

I'm running Centos in Virtualbox on Windows. Docker is installed in Centos so semaphore runs in Docker in a virtual box.
So if I wanner connect to the centos host (virtualbox) from the docker image I assumed it should be the Docker host ip (virtualbox) but that dos not seem to work.

**Comment by gcavalcante8808** [comment]
@localgod can you try to use the local ansible from the container? Its better to debug problems between the ansible and semaphore.

**Comment by gcavalcante8808** [comment]
For an initial analysis looks like you have problema with the Git clone. Try to clone your repo as well insider thr container to see what happens. To avoid ssl verify on Git you can use the command:

Git clone -c http.sslverify=False repo

**Comment by gcavalcante8808** [comment]
Closed because the user didn't replied in months.
